//>>built
{
	USERNAME: "Nom d'utilisateur",
	PASSWORD: "Mot de passe",
	REMOTENUM: "Remote nombre",
	LOGIN: "Entrer",
	LOGOUT: "Sortir",
	TIME: "Temps",
	PROFILE: "Profil",
	STATE: "�tat",
	FILE: "Fichier",
	EDIT: "�diter",
	VIEW: "Voir",
	TABS: "Languettes",
	LOADTAB: "Charger languette",
	AGENT: "Agent",
	BRAND: "Marque",
	CALLERID: "Identification",
	GOAVAILABLE: "Devenir disponible",
	ENDWRAPUP: "Finir r�capitulation",
	GORELEASED: "Devenir lib�r�...",
	QUEUERELEASE: "Lib�r� file...",
	MKOUTBOUND: "Appel sortant � ...",
	DIAL: "Appeler",
	CANCEL: "Annuler",
	ANSWER: "R�pondre",
	HANGUP: "Raccrocher",
	MAIN: "Principal",
	AGENTS: "Agents",
	QUEUES: "Files",
	EVENTLOG: "Journal de �v�nement",
	DEFAULT: "D�faut",
	IDLE: "En attente",
	RINGING: "Sonn�	",
	PRECALL: "Pr�-appel",
	ONCALL: "En appel",
	OUTGOING: "Sortant Appel",
	RELEASED: "Lib�r�",
	WARMTRANSFER: "Transfert chaud",
	WRAPUP: "R�capitulation"
}
