#!/usr/bin/env bash

BASEDIR="$( cd "$( dirname "$0" )" && pwd)"
REBAR="$BASEDIR/rebar"

function do_included_apps {	
	for file in "$BASEDIR"/include_apps/*
	do
		echo "das file:  $file"
		cd "$file"
		$REBAR "$1"
		cd "$BASEDIR"
	done
}

function post_compile {
	do_included_apps "compile"
}

function pre_compile {
	ebinDir="$BASEDIR/ebin"

	if [ ! -d "$ebinDir" ]; then
		mkdir "$ebinDir"
	fi
	
	for file in "$BASEDIR"/proto_src/*.proto
	do
		nameBase=`echo "$file" | sed -e "s/^proto_src\///"`
		nameBase="src/${nameBase}"
		if [ ! -e $nameBase -o $file -nt $nameBase ]
		then
			cp $file src/
		fi
	done
	
	# hack for include_apps
	
	# hack for reltool
	oaDir="$BASEDIR/OpenACD"
	if [ ! -d "$oaDir" ]; then
		mkdir "$oaDir"
		ln -sf ../ebin "$oaDir"/ebin
		ln -sf ../src "$oaDir"/src
		ln -sf ../include "$oaDir"/include
		ln -sf ../priv "$oaDir"/priv
		ln -sf ../deps "$oaDir"/deps
	fi
	
	# record what commit/version openacd is at
	OPENACD_COMMIT=""
	if [ -d ".git" ]
	then
		OPENACD_COMMIT=`git log -1 --pretty=format:%H`
	fi
	if [ -e "include/commit_ver.hrl" ] && [ ! $OPENACD_COMMIT ]
	then
	 exit 0
	else
		if [ ! $OPENACD_COMMIT ]
		then
			OPENACD_COMMIT="undefined"
		else
			OPENACD_COMMIT="\"$OPENACD_COMMIT\""
		fi
	fi
	echo "%% automatically generated by OpenACD precompile script.  Editing means
%% it will just get overwritten again.
	
-define(OPENACD_COMMIT, $OPENACD_COMMIT)." > include/commit_ver.hrl
}

function pre_get-deps {
	if [ "${GIT_UPDATE_DISABLED}" != "1" ]; then
		echo "Updating submodules..."
		cd "$BASEDIR"
		git submodule init && git submodule update
		cd -
	fi
}

function post_get-deps {
	do_included_apps "get-deps"
}

function pre_clean {
	rm -rf "$BASEDIR/OpenACD"
}

function post_clean {
	do_included_apps clean
}

case "$1" in
	"pre_get-deps")
		pre_get-deps;;
	"post_get-deps")
		post_get-deps;;
	"pre_compile")
		pre_compile;;
	"post_compile")
		post_compile;;
	"pre_clean")
		pre_clean;;
	"post_clean")
		post_clean;;
esac
