#!/bin/sh

cp proto_src/* src/
if [ ! -d ebin ]; then
	mkdir ebin
fi

if [ "${GIT_UPDATE_DISABLED}" != "1" ]; then
	echo "Updating submodules..."
	git submodule init && git submodule update
fi

# hack for reltool
if [ ! -d OpenACD ]; then
	mkdir OpenACD
	ln -sf ../ebin OpenACD/ebin
	ln -sf ../src OpenACD/src
	ln -sf ../include OpenACD/include
	ln -sf ../priv OpenACD/priv
	ln -sf ../deps OpenACD/deps
fi

# record what commit/version openacd is at
if [ -z "$OPENACD_COMMIT" ]; then
  OPENACD_COMMIT=`git log -1 --pretty=format:%H`
fi
echo "%% automaticall generated by OpenACD precompile script.  Editing means
%% it will just get overwritten again.

-define(OPENACD_COMMIT, \"$OPENACD_COMMIT\")." > include/commit_ver.hrl
