{success:true,
data:{identifier:"id",
label:"display",
items:[{id:"1",
	   display:"System",
	   type:"system",
	   health:{
		_type:"details",
		_value:{
			happiness:50
		}
		},
	   details:{
		_type:"details",
		_value:{
			sysdata:"goober"
		}}},
	   {id:"2",
	   display:"node1@example",
	   type:"node",
	   health:{
		_type:"details",
		_value:{
			uptime:50
		}
	   },
	   details:{
		_type:"details",
		_value:{
			location:"here"
		}
	   }
	   },
	   {id:"3",
	   display:"node2@example",
	   type:"node",
	   health:{
		_type:"details",
		_value:{
			uptime:10
		}
	   },
	   details:{
		_type:"details",
		_value:{
			location:"there"
		}
	   }},
	   {id:"4",
	   display:"queuegroup1",
	   type:"queuegroup",
	   health:{
		_type:"details",
		_value:{}
		},
	   details:{
		_type:"details",
		_value:{}
	   }},
	   {id:"5",
	   display:"queuegroup2",
	   type:"queuegroup",
	   health:{
		_type:"details",
		_value:{}
		}},
	   {id:"6",
	   display:"queue1",
	   type:"queue",
	   group:"queuegroup1",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			abandonment:10
		}}},
	   {id:"7",
	   display:"queue2",
	   type:"queue",
	   group:"queuegroup2",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			abandonment:20
		}}},
	   {id:"8",
	   display:"queue3",
	   type:"queue",
	   group:"queuegroup1",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			abandonment:50
		}}},
	   {id:"9",
	   display:"queue4",
	   type:"queue",
	   group:"queuegroup2",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			abandonment:50}
		}},
	   {id:"10",
	   display:"media1",
	   type:"media",
	   node:"node1@example",
	   queue:"queue1",
	   health:{
		_type:"details",
		_value:{
			moisteness:10
		}}},
	   {id:"11",
	   display:"media2",
	   type:"media",
	   node:"node2@example",
	   queue:"queue1",
	   health:{
		_type:"details",
		_value:{
			holdtime:50
		}}},
	   {id:"12",
	   display:"media3",
	   type:"media",
	   node:"node1@example",
	   queue:"queue2",
	   health:{
		_type:"details",
		_value:{
			holdtime:10
		}}},
	   {id:"13",
	   display:"media4",
	   node:"node2@example",
	   queue:"queue2",
	   type:"media",
	   health:{
		_type:"details",
		_value:{
			holdtime:20
		}}},
	   {id:"14",
	   display:"agentprofile1",
	   type:"agentprofile",
	   health:{
		_type:"details",
		_value:{}}},
	   {id:"15",
	   display:"agentprofile2",
	   type:"agentprofile",
	   health:{
		_type:"details",
		_value:{}}},
	   {id:"16",
	   display:"agent1",
	   type:"agent",
	   profile:"agentprofile1",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			gooberness:50
		}}},
	   {id:"17",
	   display:"agent2",
	   type:"agent",
	   profile:"agentprofile2",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			gooberness:10
		}}},
	   {id:"18",
	   display:"agent3",
	   type:"agent",
	   profile:"agentprofile1",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			gooberness:50
		}}},
	   {id:"19",
	   display:"agent4",
	   type:"agent",
	   profile:"agentprofile2",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			gooberness:20
		}}},
	   {id:"20",
	   display:"media5",
	   type:"media",
	   agent:"agent1",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			danceocity:50
		}}},
	   {id:"21",
	   display:"media6",
	   type:"media",
	   agent:"agent2",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			flameon:50
		}}}]
}}
