{success:true,
data:{identifier:"id",
label:"display",
items:[{id:"system-System",
	   display:"System",
	   type:"system",
	   health:{
		_type:"details",
		_value:{
			happiness:50
		}
		},
	   details:{
		_type:"details",
		_value:{
			sysdata:"goober"
		}}},
	   {id:"node-node1@example",
	   display:"node1@example",
	   type:"node",
	   health:{
		_type:"details",
		_value:{
			uptime:50
		}
	   },
	   details:{
		_type:"details",
		_value:{
			location:"here"
		}
	   }
	   },
	   {id:"node-node2@example",
	   display:"node2@example",
	   type:"node",
	   health:{
		_type:"details",
		_value:{
			down:100
		}
	   },
	   details:{
		_type:"details",
		_value:{
			location:"there"
		}
	   }},
	   {id:"queuegroup-queuegroup1",
	   display:"queuegroup1",
	   type:"queuegroup",
	   health:{
		_type:"details",
		_value:{}
		},
	   details:{
		_type:"details",
		_value:{}
	   }},
	   {id:"queuegroup-queuegroup2",
	   display:"queuegroup2",
	   type:"queuegroup",
	   health:{
		_type:"details",
		_value:{}
		}},
	   {id:"queue-queue1",
	   display:"queue1",
	   type:"queue",
	   group:"queuegroup1",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			abandonment:10
		}}},
	   {id:"queue-queue2",
	   display:"queue2",
	   type:"queue",
	   group:"queuegroup2",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			abandonment:20
		}}},
	   {id:"queue-queue3",
	   display:"queue3",
	   type:"queue",
	   group:"queuegroup1",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			abandonment:50
		}}},
	   {id:"queue-queue4",
	   display:"queue4",
	   type:"queue",
	   group:"queuegroup2",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			abandonment:50}
		}},
	   {id:"media-media1",
	   display:"media1",
	   type:"media",
	   node:"node1@example",
	   queue:"queue1",
	   health:{
		_type:"details",
		_value:{
			moisteness:10
		}}},
	   {id:"media-media2",
	   display:"media2",
	   type:"media",
	   node:"node2@example",
	   queue:"queue1",
	   health:{
		_type:"details",
		_value:{
			holdtime:50
		}}},
	   {id:"media-media3",
	   display:"media3",
	   type:"media",
	   node:"node1@example",
	   queue:"queue2",
	   health:{
		_type:"details",
		_value:{
			holdtime:10
		}}},
	   {id:"media-media4",
	   display:"media4",
	   node:"node2@example",
	   queue:"queue2",
	   type:"media",
	   health:{
		_type:"details",
		_value:{
			holdtime:20
		}}},
	   {id:"agentprofile-agentprofile1",
	   display:"agentprofile1",
	   type:"agentprofile",
	   health:{
		_type:"details",
		_value:{}}},
	   {id:"agentprofile-agentprofile2",
	   display:"agentprofile2",
	   type:"agentprofile",
	   health:{
		_type:"details",
		_value:{}}},
	   {id:"agent-agent1",
	   display:"agent1",
	   type:"agent",
	   profile:"agentprofile1",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			gooberness:50
		}}},
	   {id:"agent-agent2",
	   display:"agent2",
	   type:"agent",
	   profile:"agentprofile2",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			gooberness:10
		}}},
	   {id:"agent-agent3",
	   display:"agent3",
	   type:"agent",
	   profile:"agentprofile1",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			gooberness:50
		}}},
	   {id:"agent-agent4",
	   display:"agent4",
	   type:"agent",
	   profile:"agentprofile2",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			gooberness:20
		}}},
	   {id:"media-media5",
	   display:"media5",
	   type:"media",
	   agent:"agent1",
	   node:"node1@example",
	   health:{
		_type:"details",
		_value:{
			danceocity:50
		}}},
	   {id:"media-media6",
	   display:"media6",
	   type:"media",
	   agent:"agent2",
	   node:"node2@example",
	   health:{
		_type:"details",
		_value:{
			flameon:50
		}}}]
}}
