//>>built
{
	USERNAME: "Nombre de Usuario",
	PASSWORD: "Clave de Acceso",
	REMOTENUM: "Número remoto",
	LOGIN: "Ingresar",
	LOGOUT: "Salir",
	TIME: "Tiempo",
	PROFILE: "Perfil",
	STATE: "Estado",
	FILE: "Archivo",
	EDIT: "Editar",
	VIEW: "Ver",
	TABS: "Tabuladores",
	LOADTAB: "Cargar",
	AGENT: "Agente",
	BRAND: "Marca",
	CALLERID: "Identificador de Llamada",
	GOAVAILABLE: "Disponible",
	ENDWRAPUP: "Fin Post-Proceso",
	GORELEASED: "Liberar ...",
	QUEUERELEASE: "Liberar Cola...",
	MKOUTBOUND: "Llamada de salida a...",
	DIAL: "Marcar",
	CANCEL: "Cancelar",
	ANSWER: "Contestar",
	HANGUP: "Colgar",
	MAIN: "Principal",
	AGENTS: "Agentes",
	QUEUES: "Colas",
	EVENTLOG: "Bitácora de Eventos",
	DEFAULT: "Por omisión",
	IDLE: "En espera",
	RINGING: "Sonando",
	PRECALL: "Pre-llamada",
	ONCALL: "En llamada",
	OUTGOING: "Llamada de Salida",
	RELEASED: "Liberado",
	WARMTRANSFER: "Transferencia",
	WRAPUP: "Post-Proceso"
}
