require 'rake/clean'

ERLC_FLAGS = "+warn_unused_vars +warn_unused_import"

SRC = FileList['src/*.erl']
DESTDIR = 'ebin'
OBJ = SRC.pathmap("%{src,#{DESTDIR}}X.beam")

verbose(true)

directory DESTDIR

CLEAN.include(OBJ)

rule ".beam" => ["%{#{DESTDIR},src}X.erl"] do |t|
	sh "erlc -W #{ERLC_FLAGS} -o #{DESTDIR} #{t.source} "
end

task :default => [DESTDIR] + OBJ
